### ISSUE TITLE
关于attack时显存不断累加的问题

### ISSUE THREAD

**Issue by hexin5515** [Zihan-Liu-00/NeurIPS22--GraD#1]
您好，我在执行您的代码时发现随着attack的进度增加，模型占用的显存也在不断增大，这是由于代码中没有进行动态的显存回收导致的吗，还是别的原因

**Comment by Zihan-Liu-00** [comment]
您好，非常感谢您的问题。这个问题主要来自代码中一部分tensor计算被保留了计算图，进而导致了显存的堆积。我已经更新了attack.py文件，在第250行添加了with torch.no_grad():来解决这一问题。经测试修改后的代码不再导致显存占用积累。

**Comment by hexin5515** [comment]
感谢回复！
